language: node_js

sudo: required

services:
- docker

script:
- docker build -t "$DOCKER_USERNAME"/nodejs-helloworld .

after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push "$DOCKER_USERNAME"/nodejs-helloworld
