sudo: required

services:
- docker

before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker build "$DOCKER_USERNAME"/nodejs-helloworld .
- docker push "$DOCKER_USERNAME"/nodejs-helloworld
