language: node_js

sudo: required

services:
- docker

script:
- wget https://nodejs.org/dist/v8.11.1/node-v8.11.1-linux-x64.tar.xz
- wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.27-r0/glibc-2.27-r0.apk
- wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.27-r0/glibc-bin-2.27-r0.apk
- docker build -t "$DOCKER_USERNAME"/nodejs-helloworld .

after_success:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- docker push "$DOCKER_USERNAME"/nodejs-helloworld
